apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  host: kubeflow.internal.magiccityit.com
  prefix: /
  service: istio-ingressgateway.istio-system
  allow_upgrade:
  - websocket

---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: kubeflow
  namespace: emissary
  annotations:
      external-dns.ambassador-service: emissary-ingress.emissary
spec:
  hostname: "kubeflow.internal.magiccityit.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: internal-magiccityit-domain-tls
    namespace: cert-manager
