apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emissary-mapping
commonLabels:
  kustomize.component: emissary-mapping
  app.kubernetes.io/component: emissary-mapping
  app.kubernetes.io/name: emissary-mapping
resources:
- emissary-mapping.yaml
