apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: istio-logging
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  accessLogging:
    - providers:
      - name: otel
